[default]
port = 8080
# Note: Make sure to generate a new random key for production use!
secret_key = "e/33o7rRLoNpNn/xL+rdww37tb+YfvhUUtpF1H1bqu4="

[default.limits]
form = "64 KiB"
data-form = "16 GiB"
file = "16 GiB"
# Limits for specific files, e.g. "file/zip" = "32 GiB"

[default.tls]
certs = "tls/rnas.crt"
key = "tls/rnas.key"

[debug]
address = "127.0.0.1"

[release]
address = "0.0.0.0"
